name: create-ecr-repository-action
description: Create Amazon ECR repository if not exist
author: int128
inputs:
  repository:
    required: true
    description: repository name to create
runs:
  using: 'node12'
  main: 'dist/index.js'
